apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: ziadmamdouh/ci-cd-test:latest  # Make sure this matches your Docker Hub image
        ports:
        - containerPort: 8080