name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set Git Safe Directory
        run: git config --global --add safe.directory D:/actions-runner/_work/ci-cd-test/ci-cd-test

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub with retry
        shell: powershell
        run: |
          $maxRetries = 5
          $retryCount = 0
          $success = $false
          
          while ($retryCount -lt $maxRetries -and -not $success) {
            Write-Output "Attempt $($retryCount + 1): Logging in to Docker Hub..."
            echo $env:DOCKER_ACCESS_TOKEN | docker login --username ziadmamdouh --password-stdin
            if ($LASTEXITCODE -eq 0) {
              $success = $true
            } else {
              Write-Output "Login failed. Retrying in 15 seconds..."
              Start-Sleep -Seconds 15
              $retryCount++
            }
          }

          if (-not $success) {
            Write-Error "Failed to log in to Docker Hub after $maxRetries attempts."
            exit 1
          }

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ziadmamdouh/ci-cd-test:latest

      - name: Deploy to Minikube
        run: kubectl apply -f deployment.yaml