name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Set PowerShell Execution Policy (Using default Windows PowerShell)
      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force

      # Set Git Safe Directory
      - name: Set Git Safe Directory
        run: git config --global --add safe.directory D:/actions-runner/_work/ci-cd-test/ci-cd-test

      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ziadmamdouh/ci-cd-test:latest

      # Deploy to Minikube
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml