name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set Git Safe Directory
        run: git config --global --add safe.directory D:/actions-runner/_work/ci-cd-test/ci-cd-test

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub with retry
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Logging in to Docker Hub..."
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && break || sleep 15
          done
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ziadmamdouh/ci-cd-test:latest

      - name: Deploy to Minikube
        run: |
          echo "Deploying to Minikube..."
          kubectl apply -f deployment.yaml